import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from  "./provider";


const interSans = localFont({
  src: "./fonts/Inter/static/Inter_18pt-Regular.ttf",
  variable: "--font-inter-sans",
  weight: "400",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${interSans.variable} ${geistMono.variable} antialiased inter.className`}
        >
          {children}
        </body>
      </Provider>
    </html>
  );
}
